<?php
/**
 * Implements hook_menu[]
 */
function ro_first_module_menu() {
    $items = array();

    $items['examples/first-module'] = array( //this creates the URL
        'title' => 'Example Form',
        'description' => 'My first module to get started with custom modules.',
        'page callback' => 'drupal_get_form', //this is the function that will be called when the page is created. for a form, use drupal_get_form
        'page arguments' => array('ro_first_module_form'),
        'access callback' => TRUE
    );

    return $items;
}

function ro_first_module_form($form_state) {

    $form['price'] = array(
        '#type' => 'textfield', //you can find a list of available types in the form api
        '#title' => 'What is Your Price?',
        '#size' => 10,
        '#maxlength' => 10,
        '#required' => TRUE, //makes this field required
    );

    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Click Here!'),
    );

    return $form;
}

function ro_first_module_form_validate($form, &$form_state) {
    if (!($form_state['values']['price'] > 0)){
        form_set_error('price', t('Price must be a positive number.'));
    }
}

function ro_first_module_form_submit($form, &$form_state){
}